/**
 * aliensData.js
 * Camada de dados do Omnitrix Codex.
 * Mantem os dados separados da logica de renderizacao (js/app.js),
 * seguindo o padrao discutido em aula (separacao Model / View).
 *
 * Conteudo dos 60 aliens fornecido pelo proprio estudante.
 */

const omnitrixEras = {
  classico: {
    id: "classico",
    nome: "Omnitrix Protótipo",
    ano: "2005",
    corPrimaria: "#00ff66",
    corSecundaria: "#e8e8e8",
    descricao:
      "O primeiro Omnitrix encontrado por Ben Tennyson: um relógio bruto, preto e verde, preso ao pulso após a queda de uma cápsula alienígena.",
    imagem: "assets/omnitrix/omnitrix-classico.png",
    imagemAlt: "Ilustração do Omnitrix Protótipo, usado na era Clássica (2005)",
  },
  alienForce: {
    id: "alienForce",
    nome: "Omnitrix Recalibrado",
    ano: "2008",
    corPrimaria: "#00ff66",
    corSecundaria: "#1c1c1c",
    descricao:
      "Uma década depois, Azmuth recalibra o Omnitrix: design mais elegante, novo elenco de transformações e maior controle sobre a metamorfose.",
    imagem: "assets/omnitrix/omnitrix-alienforce.png",
    imagemAlt: "Ilustração do Omnitrix Recalibrado, usado na era Força Alienígena (2008)",
  },
  supremacia: {
    id: "supremacia",
    nome: "Ultimatrix",
    ano: "2010",
    corPrimaria: "#39d353",
    corSecundaria: "#0f5132",
    descricao:
      "Um dispositivo experimental em formato de manopla, capaz de evoluir um alienígena já transformado para sua forma Suprema (Ultimate).",
    imagem: "assets/omnitrix/omnitrix-supremacia.png",
    imagemAlt: "Ilustração do Ultimatrix, usado na era Supremacia Alienígena (2010)",
  },
  omniverse: {
    id: "omniverse",
    nome: "Omnitrix Definitivo",
    ano: "2013",
    corPrimaria: "#7ee081",
    corSecundaria: "#d8d8d8",
    descricao:
      "Reconstruído por Azmuth com tecnologia refinada, reúne transformações inéditas e clássicas em um único mostrador circular.",
    imagem: "assets/omnitrix/omnitrix-omniverse.png",
    imagemAlt: "Ilustração do Omnitrix Definitivo, usado na era Omniverse (2013)",
  },
};

const aliensData = {
  classico: [
    { id: "chama", nome: "Chama", especie: "Pyronita", planeta: "Pyros",
      habilidades: ["Pirocinese", "Voo"],
      feito: "Foi o primeiro alienígena no qual Ben se transformou na história." ,
      imagem: "assets/aliens/ChamaCL.png",
      imagemAlt: "Ilustração do alienígena Chama" },
    { id: "besta", nome: "Besta", especie: "Vulpimancer", planeta: "Vulpin",
      habilidades: ["Sentidos hiper-aguçados", "Agilidade"],
      feito: "Rastreou e encontrou o monstro Kraken." ,
      imagem: "assets/aliens/BestaCL.png",
      imagemAlt: "Ilustração do alienígena Besta" },
    { id: "diamante", nome: "Diamante", especie: "Petrosapien", planeta: "Petropia",
      habilidades: ["Cristalocinese", "Super-resistência"],
      feito: "Derrotou Vilgax em um combate corpo a corpo frente a frente." ,
      imagem: "assets/aliens/DiamanteCL.png",
      imagemAlt: "Ilustração do alienígena Diamante" },
    { id: "xlr8", nome: "XLR8", especie: "Kinecelerano", planeta: "Kinet",
      habilidades: ["Supervelocidade", "Reflexos"],
      feito: "Derrotou Kevin 11 pela primeira vez movimentando-se rápido demais para ele acompanhar." ,
      imagem: "assets/aliens/Xlr8CL.png",
      imagemAlt: "Ilustração do alienígena XLR8" },
    { id: "massa-cinzenta", nome: "Massa Cinzenta", especie: "Galvaniano", planeta: "Galvan Prime",
      habilidades: ["Intelecto genial", "Tamanho reduzido"],
      feito: "Sabotou peças cruciais da nave de Vilgax de dentro para fora." ,
      imagem: "assets/aliens/MassaCL.png",
      imagemAlt: "Ilustração do alienígena Massa Cinzenta" },
    { id: "quatro-bracos", nome: "Quatro Braços", especie: "Tetramand", planeta: "Khoros",
      habilidades: ["Superforça", "Ondas de choque palmares"],
      feito: "Venceu a princesa Looma e a guerreira Tini em combate físico." ,
      imagem: "assets/aliens/QuatroCL.png",
      imagemAlt: "Ilustração do alienígena Quatro Braços" },
    { id: "insectoide", nome: "Insectóide", especie: "Lepidopterrano", planeta: "Lepidopterra",
      habilidades: ["Voo", "Disparo de gosma tóxica"],
      feito: "Salvou Gwen e o Vovô Max de inúmeras quedas que seriam fatais." ,
      imagem: "assets/aliens/InseCL.png",
      imagemAlt: "Ilustração do alienígena Insectóide" },
    { id: "aquatico", nome: "Aquático", especie: "Pisccis Volann", planeta: "Pisccis",
      habilidades: ["Respiração subaquática", "Mandíbula letal"],
      feito: "Arrancou os ovos do Kraken de Jonah Melville debaixo d'água." ,
      imagem: "assets/aliens/AquaCL.png",
      imagemAlt: "Ilustração do alienígena Aquático" },
    { id: "ultra-t", nome: "Ultra T", especie: "Mecamorfo Galvânico", planeta: "Galvan B",
      habilidades: ["Fusão tecnológica", "Feixe óptico"],
      feito: "Transformou o trailer \"Lata Velha\" em uma super-máquina de combate." ,
      imagem: "assets/aliens/UltraTCL.png",
      imagemAlt: "Ilustração do alienígena Ultra T" },
    { id: "fantasmatico", nome: "Fantasmático", especie: "Ectonurita", planeta: "Anur Phaetos",
      habilidades: ["Intangibilidade", "Invisibilidade", "Possessão"],
      feito: "Quebrou o controle do Omnitrix e escapou para o mundo real." ,
      imagem: "assets/aliens/FantaCL.png",
      imagemAlt: "Ilustração do alienígena Fantasmático" },
    { id: "bala-de-canhao", nome: "Bala de Canhão", especie: "Pelarota Arburiano", planeta: "Arburia",
      habilidades: ["Forma esférica blindada"],
      feito: "Perfurou a casca indestrutível do \"Grande Carrapato\"." ,
      imagem: "assets/aliens/BalaCL.png",
      imagemAlt: "Ilustração do alienígena Bala de Canhão" },
    { id: "cipo-selvagem", nome: "Cipó Selvagem", especie: "Florauna", planeta: "Flors Verdance",
      habilidades: ["Fitocinese (manipulação de plantas)"],
      feito: "Prendeu e deteve o exército mutante do Dr. Animal." ,
      imagem: "assets/aliens/CipoCL.png",
      imagemAlt: "Ilustração do alienígena Cipó Selvagem" },
    { id: "blitzwolfer", nome: "Blitzwolfer", especie: "Loboan", planeta: "Luna Lobo",
      habilidades: ["Uivo sônico", "Garras"],
      feito: "Venceu o mutante alienígena Yenaldooshi no deserto." ,
      imagem: "assets/aliens/WolfCL.png",
      imagemAlt: "Ilustração do alienígena Blitzwolfer" },
    { id: "snare-oh", nome: "Snare-oh", especie: "Thep Khufan", planeta: "Anur Khufos",
      habilidades: ["Ataduras maleáveis", "Regeneração"],
      feito: "Sobreviveu intocado ao vácuo gélido do espaço." ,
      imagem: "assets/aliens/SnareCL.png",
      imagemAlt: "Ilustração do alienígena Snare-oh" },
    { id: "frankenstrike", nome: "Frankenstrike", especie: "Transyliano", planeta: "Anur Transyl",
      habilidades: ["Eletromagnetismo", "Superforça"],
      feito: "Enfrentou a força total do Fantasmático (Zs'Skayr) em combate espacial." ,
      imagem: "assets/aliens/FrankCL.png",
      imagemAlt: "Ilustração do alienígena Frankenstrike" },
    { id: "glutao", nome: "Glutão", especie: "Gourmando", planeta: "Peptos XI",
      habilidades: ["Ingestão de matéria", "Explosão de energia"],
      feito: "Engoliu e neutralizou o núcleo da poderosa Sub-Energia." ,
      imagem: "assets/aliens/GlutaoCL.png",
      imagemAlt: "Ilustração do alienígena Glutão" },
    { id: "clone", nome: "Clone", especie: "Splixion", planeta: "Hathor",
      habilidades: ["Multiplicação biológica infinita"],
      feito: "Confundiu todos os animais mutados do Dr. Animal atacando em bando." ,
      imagem: "assets/aliens/IdemCL.png",
      imagemAlt: "Ilustração do alienígena Clone" },
    { id: "mega-olhos", nome: "Mega Olhos", especie: "Opticóide", planeta: "Sightra",
      habilidades: ["Feixes de energia ocular variáveis"],
      feito: "Congelou inteiramente um reator de energia inimigo." ,
      imagem: "assets/aliens/MegaCL.png",
      imagemAlt: "Ilustração do alienígena Mega Olhos" },
    { id: "gigante", nome: "Gigante", especie: "To'kustar", planeta: "Tempestades Cósmicas",
      habilidades: ["Tamanho colossal", "Raio cósmico"],
      feito: "Arremessou Vilgax inteiro diretamente para a órbita do planeta." ,
      imagem: "assets/aliens/GigaCL.png",
      imagemAlt: "Ilustração do alienígena Gigante" },
  ],

  alienForce: [
    { id: "fogo-fatuo", nome: "Fogo Fátuo", especie: "Methanosiano", planeta: "Methanos",
      habilidades: ["Fitocinese", "Pirocinese", "Regeneração"],
      feito: "Conseguiu empurrar a colossal Torre de Cristal (Torre do Clima)." ,
      imagem: "assets/aliens/FogoCL.png",
      imagemAlt: "Ilustração do alienígena Fogo Fátuo" },
    { id: "eco-eco", nome: "Eco Eco", especie: "Sonorosiano", planeta: "Sonorosia",
      habilidades: ["Grito sônico", "Multiplicação independente"],
      feito: "Destruiu sozinho dezenas de tanques e frotas dos Soberanos (Highbreed)." ,
      imagem: "assets/aliens/EcoCL.png",
      imagemAlt: "Ilustração do alienígena Eco Eco" },
    { id: "enormossauro", nome: "Enormossauro", especie: "Vaxasauriano", planeta: "Terradino",
      habilidades: ["Superforça", "Alteração de tamanho"],
      feito: "Segurou no ar o peso de uma nave de guerra inteira." ,
      imagem: "assets/aliens/EnormoCL.png",
      imagemAlt: "Ilustração do alienígena Enormossauro" },
    { id: "arraia-a-jato", nome: "Arraia-à-Jato", especie: "Aerofibiano", planeta: "Aeropela",
      habilidades: ["Voo em hiperespaço", "Laser nervoso"],
      feito: "Voou na velocidade da luz para alcançar o hiperespaço." ,
      imagem: "assets/aliens/ArraiaCL.png",
      imagemAlt: "Ilustração do alienígena Arraia-à-Jato" },
    { id: "friagem", nome: "Friagem", especie: "Necrofriggiano", planeta: "Kylmyys",
      habilidades: ["Intangibilidade", "Sopro congelante"],
      feito: "Devorou o metal de espadas, escudos e fortalezas dos Cavaleiros Eternos." ,
      imagem: "assets/aliens/FriagemCL.png",
      imagemAlt: "Ilustração do alienígena Friagem" },
    { id: "cromatico", nome: "Cromático", especie: "Crystalsapien", planeta: "Petropia",
      habilidades: ["Absorção de energia/mana", "Redirecionamento"],
      feito: "Utilizou a própria luz divina para ressuscitar o planeta Petropia e seus habitantes." ,
      imagem: "assets/aliens/CromaCL.png",
      imagemAlt: "Ilustração do alienígena Cromático" },
    { id: "artropode", nome: "Artrópode", especie: "Cerebrocrustáceano", planeta: "Encephalonus IV",
      habilidades: ["Eletrocinese cerebral", "Inteligência"],
      feito: "Venceu os capangas de Vilgax calculando suas trajetórias antecipadamente." ,
      imagem: "assets/aliens/ArtroCL.png",
      imagemAlt: "Ilustração do alienígena Artrópode" },
    { id: "macaco-aranha", nome: "Macaco-Aranha", especie: "Arachnichimp", planeta: "Aranhaschimmia",
      habilidades: ["Agilidade", "Lançamento de teias"],
      feito: "Imobilizou e derrotou o astuto vilão Simian." ,
      imagem: "assets/aliens/MacacoCL.png",
      imagemAlt: "Ilustração do alienígena Macaco-Aranha" },
    { id: "gosma", nome: "Gosma", especie: "Polymorpho", planeta: "Viscosia",
      habilidades: ["Metamorfose líquida", "Acidez"],
      feito: "Agiu como pilar para segurar toda a gravidade do planeta Pisccis que entrava em colapso." ,
      imagem: "assets/aliens/GosmaCL.png",
      imagemAlt: "Ilustração do alienígena Gosma" },
    { id: "alien-x", nome: "Alien X", especie: "Sapien Celestial", planeta: "Forja da Criação",
      habilidades: ["Onipotência", "Alteração da realidade"],
      feito: "Recriou fisicamente todo o universo que havia sido destruído pela Bomba de Aniquilação (Anihilaarg)." ,
      imagem: "assets/aliens/AlienxCL.png",
      imagemAlt: "Ilustração do alienígena Alien X" },
    { id: "rath", nome: "Rath", especie: "Appoplexiano", planeta: "Appoplexia",
      habilidades: ["Força bruta brutal", "Garras", "Zero dor"],
      feito: "Humilhou os líderes guerreiros do Império Incursiano." ,
      imagem: "assets/aliens/RathCL.png",
      imagemAlt: "Ilustração do alienígena Rath" },
    { id: "estrela-polar", nome: "Estrela Polar", especie: "Biosovortiano", planeta: "Attracta",
      habilidades: ["Manipulação eletromagnética"],
      feito: "Remontou o próprio corpo do zero após ter sido explodido." ,
      imagem: "assets/aliens/PolarCL.png",
      imagemAlt: "Ilustração do alienígena Estrela Polar" },
    { id: "nanomech", nome: "Nanomech", especie: "Híbrido Humano/Nanochip", planeta: "Terra",
      habilidades: ["Encolhimento subatômico", "Lasers"],
      feito: "Destruiu a temida Rainha Nanochip atacando seu cérebro por dentro." ,
      imagem: "assets/aliens/NanoCL.png",
      imagemAlt: "Ilustração do alienígena Nanomech" },
  ],

  supremacia: [
    { id: "ameaca-aquatica", nome: "Ameaça Aquática", especie: "Orishan", planeta: "Kiusana",
      habilidades: ["Hidrocinese fortíssima", "Exoesqueleto"],
      feito: "Duelou e manteve combate equilibrado contra o Capitão Inimigo." ,
      imagem: "assets/aliens/AmeacaCL.png",
      imagemAlt: "Ilustração do alienígena Ameaça Aquática" },
    { id: "anfibio", nome: "Anfíbio", especie: "Amperi", planeta: "Tesslos",
      habilidades: ["Eletrocinese aquática", "Leitura de mentes"],
      feito: "Hackeou e fritou internamente as bases dos robôs do Aggregor." ,
      imagem: "assets/aliens/AfibioCL.png",
      imagemAlt: "Ilustração do alienígena Anfíbio" },
    { id: "armatu", nome: "Armatu", especie: "Talpaedano", planeta: "Terraexcava",
      habilidades: ["Criação de terremotos", "Escavação"],
      feito: "Partiu o chão ao meio e desmantelou equipamentos de blindagem com perfuração." ,
      imagem: "assets/aliens/ArmatuCL.png",
      imagemAlt: "Ilustração do alienígena Armatu" },
    { id: "tartagira", nome: "Tartagira", especie: "Geochelone Aerio", planeta: "Aldabra",
      habilidades: ["Aerocinese", "Imunidade a mana"],
      feito: "Resistiu sem esforço aos feitiços de magia/mana puros disparados pela Gwen." ,
      imagem: "assets/aliens/TartaCL.png",
      imagemAlt: "Ilustração do alienígena Tartagira" },
    { id: "nrg", nome: "NRG", especie: "Prypiatosian-B", planeta: "Prypiatos",
      habilidades: ["Radiação térmica extrema"],
      feito: "Devorou radiação de um núcleo nuclear prestes a explodir e o neutralizou." ,
      imagem: "assets/aliens/NRGCL.png",
      imagemAlt: "Ilustração do alienígena NRG" },
    { id: "acelerado", nome: "Acelerado", especie: "Citrakayah", planeta: "Chalybeas",
      habilidades: ["Supervelocidade", "Força de impacto"],
      feito: "Resgatou encanadores em perigo carregando-os durante combates em altíssima velocidade." ,
      imagem: "assets/aliens/AceleCL.png",
      imagemAlt: "Ilustração do alienígena Acelerado" },
    { id: "chamalien", nome: "ChamAlien", especie: "Merlinisapien", planeta: "Sauria",
      habilidades: ["Invisibilidade ótica", "Agilidade"],
      feito: "Conseguiu se infiltrar invisível dentro da fortificada Área 51." ,
      imagem: "assets/aliens/ChamalienCL.png",
      imagemAlt: "Ilustração do alienígena ChamAlien" },
    { id: "shocksquatch", nome: "Shocksquatch", especie: "Gimlinopithecus", planeta: "Pattersonea",
      habilidades: ["Eletrocinese animal", "Superforça"],
      feito: "Participou ativamente do combate contra o Alpha no crossover com Mutante Rex." ,
      imagem: "assets/aliens/SqCL.png",
      imagemAlt: "Ilustração do alienígena Shocksquatch" },
    { id: "besouro", nome: "Besouro", especie: "Oryctini", planeta: "Coleop Terra",
      habilidades: ["Ingestão de matéria", "Disparo de laser grosso"],
      feito: "Cortou a rocha de uma montanha inteira após ingerir detritos do chão." ,
      imagem: "assets/aliens/BesouroCL.png",
      imagemAlt: "Ilustração do alienígena Besouro" },
    { id: "contra-tempo", nome: "Contra-Tempo", especie: "Chronosapien", planeta: "Chronia",
      habilidades: ["Cronocinese (controle do fluxo temporal)"],
      feito: "Desfez os danos catastróficos causados pela Bomba Chronosapien no multiverso." ,
      imagem: "assets/aliens/TempoCL.png",
      imagemAlt: "Ilustração do alienígena Contra-Tempo" },
    { id: "diabrete", nome: "Diabrete", especie: "Planchaküle", planeta: "Aul-Turrhen",
      habilidades: ["Desmontagem e montagem de tecnologia em segundos"],
      feito: "Desmontou os sistemas de freio da gigantesca espaçonave de Vilgax num piscar de olhos.",
      imagem: "assets/aliens/diabrete.jpg",
      imagemAlt: "Ilustração do alienígena Diabrete",
      imagemW: 295, imagemH: 360 },
  ],

  omniverse: [
    { id: "bloxx", nome: "Bloxx", especie: "Segmentasapien", planeta: "Polyominus",
      habilidades: ["Esticar", "Criar blocos blindados"],
      feito: "Englobou-se em Ben, servindo como uma cúpula perfeita para protegê-lo de uma explosão massiva." ,
      imagem: "assets/aliens/BloxxCL.png",
      imagemAlt: "Ilustração do alienígena Bloxx" },
    { id: "gravattack", nome: "Gravattack", especie: "Galileano", planeta: "Keplorr",
      habilidades: ["Gravitocinese densa"],
      feito: "Usou sua massa gravitacional pesada para gerar um pequeno buraco negro real." ,
      imagem: "assets/aliens/GtCL.png",
      imagemAlt: "Ilustração do alienígena Gravattack" },
    { id: "crashhopper", nome: "Crashhopper", especie: "Orthopterrano", planeta: "Insetóia",
      habilidades: ["Pulos super-potentes", "Crânio blindado"],
      feito: "Bateu a cabeça e quebrou o casco de múltiplos mísseis no ar antes de acertarem o alvo.",
      imagem: "assets/aliens/crashhopper.jpg",
      imagemAlt: "Ilustração do alienígena Crashhopper",
      imagemW: 360, imagemH: 360 },
    { id: "escarabola", nome: "Escarábola", especie: "Desconhecida", planeta: "Desconhecido",
      habilidades: ["Criação de bolas de plasma magnéticas e gosmentas"],
      feito: "Absorveu e enrolou detritos explosivos capazes de engolir máquinas gigantescas." ,
      imagem: "assets/aliens/EscarCL.png",
      imagemAlt: "Ilustração do alienígena Escarábola" },
    { id: "walkatruta", nome: "Walkatruta", especie: "Ickthyperambuloid", planeta: "Gilli-Perambulous Promenade",
      habilidades: ["Pele absurdamente escorregadia"],
      feito: "Escapou consistentemente e intocado das redes de captura de caçadores intergalácticos." ,
      imagem: "assets/aliens/Walka2CL.png",
      imagemAlt: "Ilustração do alienígena Walkatruta" },
    { id: "pesky-dust", nome: "Pesky Dust", especie: "Nemuina", planeta: "Nemunimos IV",
      habilidades: ["Voo", "Pó sonífero manipulador de sonhos"],
      feito: "Colocou Khyber, o temível caçador, para dormir e arrancou os maiores segredos de sua mente." ,
      imagem: "assets/aliens/PeskyCL.png",
      imagemAlt: "Ilustração do alienígena Pesky Dust" },
    { id: "bigotoide", nome: "Bigotóide", especie: "Desconhecida", planeta: "Desconhecido",
      habilidades: ["Controle extensivo e forte dos fios de bigode"],
      feito: "Nocauteou sozinho quase todos os membros brutamontes da gangue de Fistrick." ,
      imagem: "assets/aliens/BigoCL.png",
      imagemAlt: "Ilustração do alienígena Bigotóide" },
    { id: "o-pior", nome: "O Pior", especie: "Atrociano", planeta: "Atrocius 0",
      habilidades: ["Praticamente indestrutível (apesar de sentir dor)"],
      feito: "Conseguiu vencer um alien fortíssimo por exaustão total do oponente de tanto ele o espancar." ,
      imagem: "assets/aliens/OPCL.png",
      imagemAlt: "Ilustração do alienígena O Pior" },
    { id: "cocorocoide", nome: "Cocorocóide", especie: "Desconhecida", planeta: "Desconhecido",
      habilidades: ["Esporões pontiagudos", "Maestria em combate"],
      feito: "Finalizou uma luta brutal, deixando o vilão Liam em nocaute imediato com suas pernas." ,
      imagem: "assets/aliens/CocoroCL.png",
      imagemAlt: "Ilustração do alienígena Cocorocóide" },
    { id: "feedback", nome: "Feedback", especie: "Conductoid", planeta: "Teslavorr",
      habilidades: ["Absorção", "Retenção", "Disparo elétrico pesado"],
      feito: "Absorveu a rajada letal direta da explosão do \"Big Bang\" em suas mãos." ,
      imagem: "assets/aliens/FeedCL.png",
      imagemAlt: "Ilustração do alienígena Feedback" },
    { id: "espantoide", nome: "Espantóide", especie: "Desconhecida", planeta: "Desconhecido",
      habilidades: ["Rosto paralisante que projeta os piores medos"],
      feito: "Amedrontou até as profundezas o até então destemido Zs'Skayr (Fantasmático)." ,
      imagem: "assets/aliens/EspanCL.png",
      imagemAlt: "Ilustração do alienígena Espantóide" },
    { id: "astrodactilo", nome: "Astrodáctilo", especie: "Pturbosauriano", planeta: "Terradino",
      habilidades: ["Chicotes de energia", "Jato propulsor"],
      feito: "Manejou chicotes para desmembrar em instantes as armaduras dos soldados Incursianos." ,
      imagem: "assets/aliens/AstroCL.png",
      imagemAlt: "Ilustração do alienígena Astrodáctilo" },
    { id: "bullfrag", nome: "Bullfrag", especie: "Incursiano", planeta: "Incursia",
      habilidades: ["Força avançada", "Peito blindado"],
      feito: "Enganou e seduziu a Princesa Attea, desestabilizando a guarda real Incursiana de dentro." ,
      imagem: "assets/aliens/BullCL.png",
      imagemAlt: "Ilustração do alienígena Bullfrag" },
    { id: "chocante", nome: "Chocante", especie: "Nosedeeniano", planeta: "Nosedeen Quasar",
      habilidades: ["Clonagem via eletricidade", "Possessão tecnológica"],
      feito: "Multiplicou-se rápido o suficiente para causar curto em dezenas de armadilhas das \"Megawatts\"." ,
      imagem: "assets/aliens/ChocCL.png",
      imagemAlt: "Ilustração do alienígena Chocante" },
    { id: "atomico", nome: "Atômico", especie: "Desconhecida", planeta: "Desconhecido",
      habilidades: ["Controle sobre radioatividade", "Fusão atômica"],
      feito: "Conseguiu nocautear o Macaco-Aranha Supremo e o Enormossauro Supremo de Albedo quase sem esforço." ,
      imagem: "assets/aliens/AtoCL.png",
      imagemAlt: "Ilustração do alienígena Atômico" },
    { id: "podrao", nome: "Podrão", especie: "Desconhecida", planeta: "Desconhecido",
      habilidades: ["Produção biológica de qualquer composição gasosa"],
      feito: "Liberou o gás do sono preciso capaz de derrubar instintivamente um alien gigante." ,
      imagem: "assets/aliens/PodCL.png",
      imagemAlt: "Ilustração do alienígena Podrão" },
    { id: "vompiro", nome: "Vompiro", especie: "Vladat", planeta: "Anur Vladias",
      habilidades: ["Projeção de Corrupturas (parasitas de controle)", "Voo"],
      feito: "Disparou seu parasita para controlar de imediato a vontade de seres invencíveis." ,
      imagem: "assets/aliens/VompCL.png",
      imagemAlt: "Ilustração do alienígena Vompiro" },
  ],
};